# Generated by Django 4.1.1 on 2022-09-27 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_creation', models.DateField()),
                ('date_modification', models.DateField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReleveHistorique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_rel', models.DateField()),
                ('etat_rel', models.BooleanField()),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametres.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=255)),
                ('rel_historique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.relevehistorique')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=255)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.thread')),
            ],
        ),
    ]
