# Generated by Django 4.1.1 on 2022-09-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='date_creation',
            field=models.DateField(verbose_name=['%d-%m-%Y']),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_modification',
            field=models.DateField(verbose_name=['%d-%m-%Y']),
        ),
    ]
