# Generated by Django 4.1.1 on 2022-09-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_alter_projet_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevehistorique',
            name='date_rel',
            field=models.DateField(verbose_name=['%d-%m-%Y']),
        ),
    ]
