# Generated by Django 4.1.1 on 2022-09-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0003_alter_relevehistorique_date_rel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='date_creation',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_modification',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='relevehistorique',
            name='date_rel',
            field=models.DateField(),
        ),
    ]
