# Generated by Django 4.1.1 on 2022-09-29 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0005_alter_projet_utilisateur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuivisReleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('1', 'EN_COURS'), ('2', 'TERMINE'), ('3', 'ANNULE')], default='1', max_length=2)),
                ('date_debut', models.DateField(max_length=255, null=True)),
                ('date_fin', models.DateField(max_length=255, null=True)),
                ('rel_historique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.relevehistorique')),
            ],
        ),
    ]
