# Generated by Django 4.1.1 on 2022-09-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0006_suivisreleve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivisreleve',
            name='date_debut',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='suivisreleve',
            name='date_fin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='suivisreleve',
            name='etat',
            field=models.PositiveSmallIntegerField(choices=[(1, 'EN_COURS'), (2, 'TERMINE'), (3, 'ANNULE')], default=1, max_length=12),
        ),
    ]
