# Generated by Django 4.1.1 on 2022-09-29 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0007_alter_suivisreleve_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivisreleve',
            name='date_debut',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suivisreleve',
            name='etat',
            field=models.PositiveSmallIntegerField(choices=[(1, 'EN_COURS'), (2, 'TERMINE'), (3, 'ANNULE')], default=1),
        ),
    ]
