# Generated by Django 4.1.1 on 2022-09-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0008_alter_suivisreleve_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevehistorique',
            name='date_rel',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='relevehistorique',
            name='etat_rel',
            field=models.BooleanField(default=False),
        ),
    ]
