# Generated by Django 4.1.1 on 2022-09-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0010_relevehistorique_nb_nouveau_threads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevehistorique',
            name='nb_nouveau_threads',
            field=models.IntegerField(null=True),
        ),
    ]
